# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adf3f6bfe0c392ca2f619b012dbd9730e77764e2212a65dca40d19ea438b19d95b8d4f8a63ec5c233c28e59c9d9319510f3a7c538564f1befade1d10de24762e
  facebook_app_id: 256224258080489
  facebook_app_secret: 3081bac66c0f0ba637b12f5334bb57e2
test:
  secret_key_base: 388fbdfb779c1dfba310d01a949a4d93f483363827ca2a1eef5cd9ced3f7fbcba774ff0f5dd870f3caa342986b88be3d61cfdfb4d180dae5c47b3b70db0bdc61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
